### ISSUE TITLE
Show a menu of words available in the name

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/anagrampoems#10]
# TODO
- [x] Clicking _Bust grams_ with _Kate_ in the box should take you to a page with _kate_ in the URL.
- [ ] /?key=kate should display _grams for *kate*_ on the page.
- [ ] /?key=kate should show the words that can be spelled from _kate_.

**Comment by douglasnaphas** [comment]
# Framework selection
This is the first feature I'm working on, so I'll write out the analysis for picking frameworks.
## Wishlist
Maybe _wishlist_ is better than _requirements_, because every putatively required property is negotiable. _Wishlist_ emphasizes that you might not get what you're wishing for.
1. Lambda authorizing. When a request that might need to be authenticated gets to what's serving it, it's guaranteed auth'd if it's supposed to be.

**Comment by douglasnaphas** [comment]
# ChatGPT on adding Lambda to Express + Vite
_You provided some code samples earlier in response to my question, "If I use React’s renderToString, could I combine server-side rendering with Vite.js?"_

_What code do I need to add or modify to run the Express server from an AWS Lambda function?_

Running an Express app from an AWS Lambda function involves several adjustments to ensure that the Express application can handle Lambda's event and context objects, as well as to properly respond through Lambda's callback mechanism. You'll use libraries like `aws-serverless-express` or `serverless-http` to bridge Express and AWS Lambda. Below, I'll show you how to adapt your server-side code using the `serverless-http` package, which is simpler and more flexible for many use cases.

### Step-by-Step Guide

**Step 1: Install serverless-http**
First, add the `serverless-http` library to your project. This library is designed to handle the translation between your Node.js server (e.g., Express) and the AWS Lambda handler.

```bash
npm install serverless-http
```

**Step 2: Modify Your Express Application for AWS Lambda**
Assuming you have an existing Express application setup, you'll need to modify it slightly so it can be invoked by AWS Lambda. Here’s how you can do it:

1. **Create the Express App (if not already created)**:
   ```javascript
   const express = require('express');
   const app = express();

   app.get('/', (req, res) => {
     res.send('Hello from Express on AWS Lambda!');
   });

   module.exports = app;
   ```

2. **Wrap the Express app with serverless-http**:
   Create a new file, perhaps called `lambda.js`, to be the entry point for Lambda:

   ```javascript
   const serverless = require('serverless-http');
   const app = require('./app');  // Importing your Express app

   module.exports.handler = serverless(app);
   ```

**Step 3: Configure the AWS Lambda Function**
Now, you'll need to set up your Lambda function on AWS. Here’s a brief overview:

- **Create a new Lambda function** in the AWS Management Console.
- **Set the runtime** to Node.js.
- **Upload your code** or deploy through AWS CLI or an integration tool like Serverless Framework or AWS SAM.
- **Set the handler** to `lambda.handler` (matching the exported handler in your `lambda.js`).

**Step 4: Set Up API Gateway**
To expose your Lambda function via HTTP:

- **Create a new API** in AWS API Gateway.
- **Create a new resource and method** (e.g., GET method for the root path `/`).
- **Connect the API Gateway to your Lambda function**.
- **Deploy the API** to make it publicly accessible.

**Step 5: Deploy and Test**
After setting up the Lambda function and API Gateway:

- Deploy your API if not already deployed.
- Test the endpoint provided by API Gateway to ensure your Express application is functioning as expected.

### Additional Notes

- **Environment Variables**: Configure any necessary environment variables through the Lambda function settings in the AWS Console.
- **Permissions**: Make sure your Lambda function has the appropriate permissions, especially if it needs to interact with other AWS services.
- **Logging**: Logs can be viewed in AWS CloudWatch to monitor the behavior and troubleshoot if needed.

This setup leverages `serverless-http` to run an Express application on AWS Lambda, allowing you to utilize existing Express-based server-side rendering setups in a serverless environment effectively.
